### ISSUE TITLE
[PE-D][Tester B] Long string in addExpense

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-2/tp#102]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/SebasFok/ped/main/files/7f632f5d-0cd2-4c53-b8ae-09c64006b421.png)

Adding a long string messes with the formatting or the table

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: SebasFok/ped#4

**Comment by BenedictChannn** [comment]
This is likely due to the size of the screen that you are using to view this. Will change the max description length
