### ISSUE TITLE
[PE-D][Tester B] Ctrl + C

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-W12-2/tp#95]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
pressing ctrl + c closes the programme with a lot of random messages

![image.png](https://raw.githubusercontent.com/SebasFok/ped/main/files/dc16fb8c-72c1-4fd8-a44e-1966fe58b75a.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: SebasFok/ped#2

**Comment by BenedictChannn** [comment]
Ctrl + C terminates the program immediately but does not produce the above error messages. Will fix the termination issue

**Comment by mcmc101001** [comment]
Think bug shows up as ctrl-D on some devices, I had this problem, fixed in PR linked
